BeatyOfNature/Models/WildCat.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace BeatyOfNature.Models
{
    public class WildCat
    {
        [Required]
        public int Id { get; set; }
        
        [Required]
        [DataType(DataType.Text)]
        public string Category { get; set; }

        [Required]
        [DataType(DataType.Text)]
        [StringLength(maximumLength: 200, MinimumLength = 5)]
        public string Title { get; set; }

        [DataType(DataType.MultilineText)]
        public string Description { get; set; }

        [DataType(DataType.ImageUrl)]
        [Display(Name = "ImageUrl")]
        public string ImageUrl { get; set; }

    }
}

BeatyOfNature/Controllers/WildCatsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BeatyOfNature.Models;
using System.IO;


namespace BeatyOfNature.Controllers
{ 
    public class WildCatsController : Controller
    {
        
        private WildCatsDataContext db = new WildCatsDataContext();
        string path = null;
        //
        // GET: /WildCats/

        public ViewResult Index()
        {
            return View(db.WildCats.ToList());
        }

        //
        // GET: /WildCats/Details/5

        public ViewResult Details(int id)
        {
            WildCat wildcat = db.WildCats.Find(id);
            return View(wildcat);
        }

        //
        // GET: /WildCats/Create
        [HttpGet]
        public ActionResult Create()
        {
            return View();
        } 

        //
        // POST: /WildCats/Create

        [HttpPost]
        public ActionResult Create(WildCat wildcat)
        {
            if (ModelState.IsValid)
            {
                //try
                //{
                //    var fileName = Path.GetFileName(ImageUrl.FileName);
                //    //path = AppDomain.CurrentDomain.BaseDirectory + "Images\\" + fileName;
                //    path = HttpContext.Server.MapPath("~/Images/" + fileName);
                //    //path = Url.Content("~/UserContent/" + fileName);
                //    ImageUrl.SaveAs(path);
                //   // wildcat.ImageUrl = Url.Content("~/Images/" + fileName);
                //}
                //catch
                //{
                //    ViewBag.errorMessage = "Upload Fail";
                //}
                //wildcat.ImageUrl = Url.Content("~/UserContent/" + fileName);
                db.WildCats.Add(wildcat);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(wildcat);
        }
       
        //
        // GET: /WildCats/Edit/5
 
        public ActionResult Edit(int id)
        {
            WildCat wildcat = db.WildCats.Find(id);
            return View(wildcat);
        }

        //
        // POST: /WildCats/Edit/5

        [HttpPost]
        public ActionResult Edit(WildCat wildcat)
        {
            if (ModelState.IsValid)
            {
                
                db.Entry(wildcat).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(wildcat);
        }

        //
        // GET: /WildCats/Delete/5
 
        public ActionResult Delete(int id)
        {
            WildCat wildcat = db.WildCats.Find(id);
            return View(wildcat);
        }

        //
        // POST: /WildCats/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {            
            WildCat wildcat = db.WildCats.Find(id);
            db.WildCats.Remove(wildcat);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
    
}

BeatyOfNature/Views/WildCats/Create.cshtml
@model BeatyOfNature.Models.WildCat

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>

@using (Html.BeginForm("Create", "WildCats", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.ValidationSummary(true)
    <fieldset>
        <legend>WildCat</legend>
        <div class="editor-label">
            @Html.LabelFor(model => model.Title)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Title)
            @Html.ValidationMessageFor(model => model.Title)
        </div>
        <div class="editor-label">
            @Html.LabelFor(model => model.Category)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Category)
            @Html.ValidationMessageFor(model => model.Category)
        </div>

        

        <div class="editor-label">
            @Html.LabelFor(model => model.Description)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Description)
            @Html.ValidationMessageFor(model => model.Description)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.ImageUrl)
        </div>
        <div class="editor-field">
            @*  <input type="file" name="ImageUrl" id="ImageUrl" />*@
          @Html.EditorFor(model => model.ImageUrl)
            @Html.ValidationMessageFor(model => model.ImageUrl)
        </div>

        @ViewBag.chpath

        <p>
            <input type="submit" value="Create" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

BeatyOfNature/Views/WildCats/Delete.cshtml
@model BeatyOfNature.Models.WildCat

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<fieldset>
    <legend>WildCat</legend>

    <div class="display-label">Category</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Category)
    </div>

    <div class="display-label">Title</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Title)
    </div>

    <div class="display-label">Description</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Description)
    </div>

    <div class="display-label">ImageUrl</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.ImageUrl)
    </div>
</fieldset>
@using (Html.BeginForm()) {
    <p>
        <input type="submit" value="Delete" /> |
        @Html.ActionLink("Back to List", "Index")
    </p>
}

BeatyOfNature/Views/WildCats/Details.cshtml
@model BeatyOfNature.Models.WildCat

@{
    ViewBag.Title = "Details";
}

<fieldset>
    <legend>@Html.DisplayFor(model => model.Title)</legend>
    <div class="display-field">
        @Html.DisplayFor(model => model.Category)
    </div>
    <br />
    <div class="row-fluid">
        <div class="span4">
            <img src="@Html.DisplayFor(model => model.ImageUrl)" width="400px"/>
        </div>
        <div class="span8">
            <div class="display-field">
                @Html.DisplayFor(model => model.Description)
            </div>
        </div>
    </div>
</fieldset>

BeatyOfNature/Views/WildCats/Edit.cshtml
@model BeatyOfNature.Models.WildCat

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)
    <fieldset>
        <legend>WildCat</legend>

        @Html.HiddenFor(model => model.Id)

        <div class="editor-label">
            @Html.LabelFor(model => model.Category)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Category)
            @Html.ValidationMessageFor(model => model.Category)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Title)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Title)
            @Html.ValidationMessageFor(model => model.Title)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Description)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Description)
            @Html.ValidationMessageFor(model => model.Description)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.ImageUrl)
        </div>
        <div class="editor-field">
           @* <input type="file" name="ImageUrl" id="ImageUrl" />*@
          @Html.EditorFor(model => model.ImageUrl)
            @Html.ValidationMessageFor(model => model.ImageUrl)
        </div>

        <p>
            <input type="submit" value="Save" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

BeatyOfNature/Views/WildCats/Index.cshtml
@model IEnumerable<BeatyOfNature.Models.WildCat>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>


@foreach (var item in Model) {
            <b>Title:</b>
            @Html.DisplayFor(modelItem => item.Title)<br />
            <b>Description</b>
            @Html.DisplayFor(modelItem => item.Description)<br />
            <b>Caption</b>
            @Html.DisplayFor(modelItem => item.Category)<br />
            <b>Image</b>
            <img src="@item.ImageUrl" width="130px;"/><br />
         <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    <br /><br />
        <div class="border-div"></div>
    
}